#!/usr/bin/env bash
# API_HOST="localhost" API_PORT="5000" BioMrc_USER="BioMrc" BioMrc_PWD="BioMrc2024" BioMrc_HOST="localhost" BioMrc_DB="BioMrcDB" SESSION_EXP="day" SESSION_NAME="session_id"
python3 -m api.v1.app
