#!/usr/bin/env bash
if [ $# -lt 1 ]; then
    echo "Usage: $0 <api/Console>"
    exit 1
fi

Run=$2
if [[ "$1" == 'api' ]]; then
    API_HOST="localhost" API_PORT="5000" BioMrc_USER="BioMrc" BioMrc_PWD="BioMrc2024" BioMrc_HOST="localhost" BioMrc_DB="BioMrcDB" python3 -m api.v1.app
else
    BioMrc_USER="BioMrc" BioMrc_PWD="BioMrc2024" BioMrc_HOST="localhost" BioMrc_DB="BioMrcDB" python3 console.py
fi
